### ISSUE TITLE
Over-Write [BUG]

### ISSUE THREAD

**Issue by Narulacodes** [xor-editor/xor#6]
# Explain The Issue
When Writing, Css,Xml and JS. You can see the preview text show what you wrote.
My Understanding is that it isn't suposed to do that.

# Steps to reprouduce

- Fix Issue

# ScreenShot 
![ww](https://user-images.githubusercontent.com/21000033/35203943-daa25e20-fef8-11e7-9d64-c89c16d9093f.png)

**Comment by Nanomotion** [comment]
You're supposed to enter HTML into the editor, not plain CSS. If you want to insert styling you need to use the `<style>` tag, and if you want to enter JavaScript, you need to use it in a `<script>` tag.

**Comment by Narulacodes** [comment]
So this is only a html editor?

**Comment by Nanomotion** [comment]
Yes, and it has support for different flavors such as XHTML, and supports CSS and JS.

![capture](https://user-images.githubusercontent.com/19719195/35252276-b1b919b2-ffad-11e7-8fe4-848509660d9f.PNG)
